version: '3'

services:
    db:
        build: .
        ports:
            - '5432:5432'
        volumes:
            - db-data:/var/lib/postgresql/data
        environment:
            POSTGRES_USER: nosconformes
            POSTGRES_PASSWORD: n0W7I8$zK#9s
            POSTGRES_DB: nosconformes
        networks:
            - mynetwork

    app:
        build: .
        ports:
            - '3333:3333'
        environment:
            POSTGRES_USER: nosconformes
            POSTGRES_PASSWORD: n0W7I8$zK#9s
            POSTGRES_DB: nosconformes
            POSTGRES_HOST: db
        depends_on:
            - db
        networks:
            - mynetwork
        # command: npm run start:dev

volumes:
    db-data:

networks:
    mynetwork:
        driver: bridge
