version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nosconformes
    ports:
      - "3000:3000"
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=nosconformes
      - POSTGRES_PASSWORD=nosconformes
      - POSTGRES_DB=nosconformes
    depends_on:
      - postgres
  postgres:
    image: postgres:13-alpine
    container_name: nosconformesdb
    environment:
      - POSTGRES_USER=nosconformes
      - POSTGRES_PASSWORD=nosconformes
      - POSTGRES_DB=nosconformes
